### ISSUE TITLE
Won't compile with GNU Octave, version 6.4.0

### ISSUE THREAD

**Issue by endoveg** [shsajjadi/OctaveCoder#43]
`/home/disk/ia-rjt/GaussNewtonMinLeakage.cc: In constructor ‘coder::Symbol::Symbol(const char*, const char*, const char*, coder::file_type)’:
/home/disk/ia-rjt/GaussNewtonMinLeakage.cc:2816:30: error: ‘::load_fcn_from_file’ has not been declared; did you mean ‘octave::load_fcn_from_file’?
 2816 |             = OCTAVE_DEPR_NS load_fcn_from_file (fullname, path, "", "", fcn_name, true);
      |                              ^~~~~~~~~~~~~~~~~~
      |                              octave::load_fcn_from_file
In file included from /home/disk/ia-rjt/GaussNewtonMinLeakage.cc:1715:
/usr/include/octave-6.4.0/octave/parse.h:680:3: note: ‘octave::load_fcn_from_file’ declared here
  680 |   load_fcn_from_file (const std::string& file_name,
      |   ^~~~~~~~~~~~~~~~~~
warning: mkoctfile: building exited with failure status
error: coder: compile error`

**Comment by shsajjadi** [comment]
Thanks for reporting the bug!
It is a regression beginning from coder 1.7 that omits prepending octave:: namespace to the function "load_fcn_from_file".

I pushed the following fix [7a5177](https://github.com/shsajjadi/OctaveCoder/commit/7a517790b8681fea445150ce7b993a1fd4432feb).

You can clone the repository and make a tar.gz from the repository and install the package before the release of a new version.
